[package]
name = "hadamard-core"
version = "0.1.0"
edition = "2021"
authors = ["Yağız Yağlı"]
description = "Enterprise-grade, ultra-lightweight quantum database query engine written in Rust."
license = "Apache-2.0"

[lib]
name = "hadamard_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
tokio = { version = "1.38", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
atomic-counter = "1.0.1" # Fixed: Swapped underscore (_) with hyphen (-) to match official crates.io register
pyo3 = { version = "0.21", features = ["extension-module"], optional = true }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
